"""
Deterministic mapping from source tags/topics to (domain, category).

Keys are lowercased. Both HuggingFace tags, GitHub topics, Product Hunt topics,
and common keywords are included. Add new mappings here as new tags appear in
the wild.
"""

from __future__ import annotations

# (domain, category)
TAG_MAP: dict[str, tuple[str, str]] = {
    # ── Audio & Speech ──────────────────────────────────────────────
    "text-to-speech": ("audio", "text-to-speech"),
    "speech-synthesis": ("audio", "text-to-speech"),
    "tts": ("audio", "text-to-speech"),
    "automatic-speech-recognition": ("audio", "speech-to-text"),
    "speech-to-text": ("audio", "speech-to-text"),
    "asr": ("audio", "speech-to-text"),
    "whisper": ("audio", "speech-to-text"),
    "voice-cloning": ("audio", "voice-cloning"),
    "voice-clone": ("audio", "voice-cloning"),
    "music-generation": ("audio", "music-generation"),
    "music": ("audio", "music-generation"),
    "audio-enhancement": ("audio", "audio-enhancement"),
    "audio-separation": ("audio", "audio-separation"),
    "stem-separation": ("audio", "audio-separation"),
    "audio": ("audio", "audio-enhancement"),
    "midi": ("audio", "music-generation"),
    "singing": ("audio", "music-generation"),

    # ── Image ───────────────────────────────────────────────────────
    "image-generation": ("image", "image-generation"),
    "text-to-image": ("image", "image-generation"),
    "stable-diffusion": ("image", "image-generation"),
    "flux": ("image", "image-generation"),
    "diffusion": ("image", "image-generation"),
    "image-editing": ("image", "image-editing"),
    "image-to-image": ("image", "image-editing"),
    "inpainting": ("image", "image-editing"),
    "outpainting": ("image", "image-editing"),
    "segmentation": ("image", "image-editing"),
    "image-segmentation": ("image", "image-editing"),
    "image-upscaling": ("image", "image-upscaling"),
    "upscaler": ("image", "image-upscaling"),
    "super-resolution": ("image", "image-upscaling"),
    "enhancer": ("image", "image-upscaling"),
    "background-removal": ("image", "background-removal"),
    "remove-background": ("image", "background-removal"),
    "face-swap": ("image", "face-swap"),
    "faceswap": ("image", "face-swap"),
    "ocr": ("image", "ocr-recognition"),
    "optical-character-recognition": ("image", "ocr-recognition"),
    "image-classification": ("image", "image-generation"),
    "object-detection": ("image", "ocr-recognition"),
    "controlnet": ("image", "image-generation"),
    "lora": ("image", "image-generation"),
    "sdxl": ("image", "image-generation"),
    "image-to-3d": ("3d", "3d-generation"),

    # ── Video ───────────────────────────────────────────────────────
    "video-generation": ("video", "video-generation"),
    "text-to-video": ("video", "video-generation"),
    "image-to-video": ("video", "video-generation"),
    "video-editing": ("video", "video-editing"),
    "video-processing": ("video", "video-editing"),
    "video-enhancement": ("video", "video-enhancement"),
    "video-upscaling": ("video", "video-enhancement"),
    "animation": ("video", "animation"),
    "animate": ("video", "animation"),
    "lip-sync": ("video", "lip-sync"),
    "lipsync": ("video", "lip-sync"),
    "talking-face": ("video", "lip-sync"),

    # ── 3D & Spatial ────────────────────────────────────────────────
    "3d-generation": ("3d", "3d-generation"),
    "3d-reconstruction": ("3d", "3d-reconstruction"),
    "3d-object-detection": ("3d", "3d-generation"),
    "3d-detection": ("3d", "3d-generation"),
    "depth-estimation": ("3d", "depth-estimation"),
    "point-cloud": ("3d", "3d-reconstruction"),
    "3d-bounding-box": ("3d", "3d-generation"),
    "nerf": ("3d", "3d-reconstruction"),
    "gaussian-splatting": ("3d", "3d-reconstruction"),

    # ── Text & Language ─────────────────────────────────────────────
    "chatbot": ("text", "chatbots-assistants"),
    "chatbots": ("text", "chatbots-assistants"),
    "conversational-ai": ("text", "chatbots-assistants"),
    "llm": ("text", "chatbots-assistants"),
    "large-language-model": ("text", "chatbots-assistants"),
    "language-model": ("text", "chatbots-assistants"),
    "text-generation": ("text", "chatbots-assistants"),
    "writing": ("text", "writing-content"),
    "copywriting": ("text", "writing-content"),
    "content-generation": ("text", "writing-content"),
    "translation": ("text", "translation"),
    "machine-translation": ("text", "translation"),
    "nllb": ("text", "translation"),
    "summarization": ("text", "summarization"),
    "text-summarization": ("text", "summarization"),
    "code-generation": ("text", "code-generation"),
    "code": ("text", "code-generation"),
    "coding": ("text", "code-generation"),
    "code-assistant": ("text", "code-generation"),
    "search": ("text", "search-retrieval"),
    "retrieval": ("text", "search-retrieval"),
    "rag": ("text", "search-retrieval"),
    "semantic-search": ("text", "search-retrieval"),
    "natural-language-processing": ("text", "chatbots-assistants"),
    "nlp": ("text", "chatbots-assistants"),
    "question-answering": ("text", "chatbots-assistants"),
    "sentiment-analysis": ("text", "chatbots-assistants"),

    # ── Data & Analytics ────────────────────────────────────────────
    "data-analysis": ("data", "data-analysis"),
    "data-visualization": ("data", "data-visualization"),
    "document-processing": ("data", "document-processing"),
    "pdf": ("data", "document-processing"),
    "financial-analysis": ("data", "financial-analysis"),
    "finance": ("data", "financial-analysis"),
    "stock": ("data", "financial-analysis"),
    "trading": ("data", "financial-analysis"),
    "stocks": ("data", "financial-analysis"),

    # ── Developer Tools ─────────────────────────────────────────────
    "machine-learning": ("dev", "ml-frameworks"),
    "ml": ("dev", "ml-frameworks"),
    "deep-learning": ("dev", "ml-frameworks"),
    "pytorch": ("dev", "ml-frameworks"),
    "tensorflow": ("dev", "ml-frameworks"),
    "transformers": ("dev", "ml-frameworks"),
    "model-hosting": ("dev", "model-hosting"),
    "inference": ("dev", "model-hosting"),
    "fine-tuning": ("dev", "fine-tuning"),
    "finetuning": ("dev", "fine-tuning"),
    "qlora": ("dev", "fine-tuning"),
    "sft": ("dev", "fine-tuning"),
    "dpo": ("dev", "fine-tuning"),
    "gguf": ("dev", "model-hosting"),
    "onnx": ("dev", "model-hosting"),
    "leaderboard": ("dev", "evaluation-benchmarks"),
    "evaluation": ("dev", "evaluation-benchmarks"),
    "benchmark": ("dev", "evaluation-benchmarks"),
    "agents-automation": ("dev", "agents-automation"),
    "agent": ("dev", "agents-automation"),
    "smolagents": ("dev", "agents-automation"),
    "smolagent": ("dev", "agents-automation"),
    "agent-course": ("dev", "agents-automation"),
    "mcp-server": ("dev", "mcp-tools"),
    "mcp": ("dev", "mcp-tools"),
    "rl-environment": ("dev", "agents-automation"),
    "openenv": ("dev", "agents-automation"),

    # ── Multimodal ──────────────────────────────────────────────────
    "multimodal": ("multimodal", "vision-language"),
    "vision-language": ("multimodal", "vision-language"),
    "visual-question-answering": ("multimodal", "vision-language"),
    "generative-ai": ("multimodal", "omni-models"),
    "omni": ("multimodal", "omni-models"),

    # ── Science & Research ──────────────────────────────────────────
    "healthcare": ("science", "healthcare-medical"),
    "medical": ("science", "healthcare-medical"),
    "medgemma": ("science", "healthcare-medical"),
    "robotics": ("science", "robotics"),
    "embodied-ai": ("science", "robotics"),
    "scientific-computing": ("science", "scientific-computing"),
    "physics": ("science", "scientific-computing"),
    "chemistry": ("science", "scientific-computing"),
    "biology": ("science", "scientific-computing"),
    "protein": ("science", "scientific-computing"),
    "drug": ("science", "healthcare-medical"),

    # ── Broad AI tags → Developer Tools by default ──────────────────
    "ai": ("dev", "ml-frameworks"),
    "artificial-intelligence": ("dev", "ml-frameworks"),
    "ai-agents": ("dev", "agents-automation"),
    "ai-agent": ("dev", "agents-automation"),
    "agentic-ai": ("dev", "agents-automation"),
    "agents": ("dev", "agents-automation"),
    "langchain": ("dev", "agents-automation"),
    "langgraph": ("dev", "agents-automation"),
    "autogen": ("dev", "agents-automation"),
    "crewai": ("dev", "agents-automation"),
    "openai": ("dev", "ml-frameworks"),
    "openai-api": ("dev", "ml-frameworks"),
    "gpt": ("text", "chatbots-assistants"),
    "gpt-3": ("text", "chatbots-assistants"),
    "gpt-4": ("text", "chatbots-assistants"),
    "gpt-4o": ("text", "chatbots-assistants"),
    "chatgpt": ("text", "chatbots-assistants"),
    "claude": ("text", "chatbots-assistants"),
    "gemini": ("text", "chatbots-assistants"),
    "llama": ("text", "chatbots-assistants"),
    "ollama": ("dev", "model-hosting"),
    "mistral": ("text", "chatbots-assistants"),
    "copilot": ("text", "code-generation"),
    "claude-code": ("text", "code-generation"),
    "codex": ("text", "code-generation"),
    "cursor": ("text", "code-generation"),
    "developer-tools": ("dev", "ml-frameworks"),
    "prompt-engineering": ("text", "chatbots-assistants"),
    "mlops": ("dev", "ml-frameworks"),
    "embeddings": ("text", "search-retrieval"),
    "vector-database": ("text", "search-retrieval"),
    "ai-assistant": ("text", "chatbots-assistants"),
    "ai-safety": ("dev", "evaluation-benchmarks"),
    "transformer": ("dev", "ml-frameworks"),
    "attention-mechanism": ("dev", "ml-frameworks"),
    "bert": ("text", "chatbots-assistants"),
    "neural-network": ("dev", "ml-frameworks"),
    "computer-vision": ("image", "image-generation"),
    "speech-recognition": ("audio", "speech-to-text"),
    "reinforcement-learning": ("dev", "ml-frameworks"),
    "automation": ("dev", "agents-automation"),
    "llms": ("text", "chatbots-assistants"),
    "saas": ("dev", "ml-frameworks"),
    "productivity": ("text", "writing-content"),
    "cli": ("dev", "ml-frameworks"),
    "awesome-list": ("dev", "ml-frameworks"),
    "security": ("dev", "ml-frameworks"),

    # ── Python/Web framework tags → skip (classified via other tags) ─
}

# Tags to skip — these don't help with classification
SKIP_TAGS: set[str] = {
    "gradio",
    "docker",
    "static",
    "streamlit",
    "region:us",
    "region:eu",
    "not-for-all-audiences",
    "anycoder",
    "deepsite-v3",
    "research-article-template",
    "research paper",
    "scientific paper",
    "jax-diffusers-event",
    "whisper-event",
    "competition",
    "dataset",
    "front-end",
    "webgl",
    "python",
    "typescript",
    "javascript",
    "rust",
    "golang",
    "react",
    "nextjs",
    "fastapi",
    "android",
    "github",
    "huggingface",
    "open-source",
    "show-hn",
}
